# Documentation: https://github.com/zakodium/workflows#release

name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      packages: write
    uses: zakodium/workflows/.github/workflows/release.yml@release-v1
    with:
      npm: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
