# push-button triggered action that runs npm version {major,minor,patch}, git push --follow-tags and finally npm publish
# see https://github.com/marketplace/actions/npm-bump for more info

name: Version and Release

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'Enter major, minor, or patch'
        required: true

env:
  node_version: lts/*
  
concurrency: # prevent concurrent releases
  group: npm-bump
  cancel-in-progress: true

jobs:
  version_and_release:
    permissions:
      contents: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    outputs:
      tagName: ${{ steps.npm-bump.outputs.release_tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'
    - run: npm i
    - run: npm test
    - name: Version and publish to npm
      id: npm-bump
      uses: bcomnes/npm-bump@v2
      with:
        git_email: marcll@vt.edu
        git_username: 777arc
        newversion: ${{ github.event.inputs.newversion }} # passed as interactive variable (see above)
        push_version_commit: true # if your prePublishOnly step pushes git commits, you can omit this input or set it to false.
        github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }} # built in actions token.  Passed to gh-release if in use.
        npm_token: ${{ secrets.NPM_TOKEN }} # user set secret token generated at npm
    - run: echo ${{ steps.npm-bump.outputs.release_tag }}